name: win_module
description: A package to build multiple moudles into one release(exe,zip) in windows
version: 1.0.0
homepage: https://github.com/rtugeek/win_module

platforms:
  windows:

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  pubspec_parse: ^1.2.1
  yaml: ^3.1.0
  args: ^2.2.0
  colorize: ^3.0.0
  flutter_app_builder: ^0.2.3
  pub_semver: ^2.1.1
  flutter_app_packager: ^0.2.4
  logging: ^1.0.2
  io: ^1.0.3
  recase: ^4.0.0
dev_dependencies:
executables:
  win_module: main
